# Generated by Django 4.2.1 on 2023-06-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_number", models.IntegerField()),
                ("name", models.CharField(max_length=100)),
                ("personal_number", models.IntegerField()),
                ("nationality", models.CharField(max_length=50)),
                ("job_title", models.CharField(max_length=100)),
                ("department", models.CharField(max_length=100)),
                ("administration", models.CharField(max_length=100)),
                ("qualification", models.CharField(max_length=100)),
                ("major", models.CharField(max_length=100)),
                ("degree", models.CharField(max_length=100)),
                ("job_description", models.TextField()),
                ("job_duties", models.TextField()),
                ("job_objectives", models.TextField()),
                ("suggested_training", models.TextField()),
                ("job_designation", models.CharField(max_length=100)),
            ],
        ),
    ]
