# Generated by Django 4.2.1 on 2023-06-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="administration",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="employee",
            name="department",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="employee",
            name="job_designation",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="employee",
            name="job_title",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="employee",
            name="major",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="employee",
            name="name",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="employee",
            name="nationality",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="employee",
            name="qualification",
            field=models.CharField(max_length=150),
        ),
    ]
