# Generated by Django 4.2.2 on 2023-08-11 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_employee_job_designation_and_more'),
    ]

    operations = [
    ]
