# Generated by Django 4.2.2 on 2023-08-11 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20230811_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=100)),
                ('code', models.TextField()),
                ('group_type', models.CharField(max_length=100)),
                ('general_group', models.CharField(max_length=100)),
                ('job_location', models.TextField()),
                ('job_responsibilities', models.TextField()),
                ('job_objectives', models.TextField()),
                ('job_requirements', models.TextField()),
                ('description', models.TextField()),
                ('generated', models.TextField()),
                ('objectives', models.TextField()),
                ('skills', models.TextField()),
                ('training', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='job_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobtitle'),
        ),
    ]
